ITEM.name = "쇠고기 스프"
ITEM.model = "models/props_c17/metalPot001a.mdl"
ITEM.hungerAmount = 100
ITEM.mustCooked = true
ITEM.foodDesc = "쇠고기가 많이들어간 스프입니다."
ITEM.quantity = 8
ITEM.width = 2
ITEM.price = 300
ITEM.height = 2
ITEM.staminaAmount = 15